### ISSUE TITLE
DISCLAIMER.PD is missing

### ISSUE THREAD

**Issue by dracc** [fgsfdsfgs/pbgl#1]
Not sure if this is issue-worthy, but I couldn't help but notice that DISCLAIMER.PD as mentioned in https://github.com/fgsfdsfgs/pbgl/blob/17a728813375f36e8c93f8b0fba10849e5108e07/include/GL/gl.h#L4 is missing.

**Comment by fgsfdsfgs** [comment]
That's true. I pulled that file from my MinGW install since it's public domain and couldn't find the disclaimer file, so I didn't bother.
It seems that [it says much of the same](https://github.com/Alexpux/mingw-w64/blob/master/DISCLAIMER.PD) as what's written in `gl.h`, so I'll probably just paste it in there.
